# Podfile content
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'FoOps' do
    rn_path = '../node_modules/react-native'
    rn_maps_path = '../node_modules/react-native-maps'

    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [ 
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',   
    ]  
    pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
    pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

    pod 'react-native-maps', path: rn_maps_path
    pod 'react-native-google-maps', path: rn_maps_path
    pod 'GoogleMaps'  
    pod 'Google-Maps-iOS-Utils' 
    
#  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

 # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'


  #pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  #pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == "RNSVG"
      target.remove_from_project
    end
    if target.name == "yoga"
      target.remove_from_project
    end

  end
end
